name: Build & Push Docker Images
# ONLY run when the "OneShot CI" workflow completes
on:
  workflow_run:
    workflows: ["OneShot CI"]
    types:
      - completed
jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    # Only run if the tests passed
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # BACKEND
      - name: Build and push Backend
        uses: docker/build-push-action@v5
        with:
          context: .  # Build from Root
          file: Back/Dockerfile
          push: true
          tags: threshact/oneshot-backend:latest

      # FRONTEND
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./front
          file: front/Dockerfile
          push: true
          tags: threshact/oneshot-frontend:latest
